/** @type {import('next').NextConfig} */
const nextConfig = {
    env: {
      NEXT_PUBLIC_EXPENSE_TRACKER_API_KEY: process.env.NEXT_PUBLIC_EXPENSE_TRACKER_API_KEY,
      NEXT_PUBLIC_EXPENSE_TRACKER_AUTH_DOMAIN: process.env.NEXT_PUBLIC_EXPENSE_TRACKER_AUTH_DOMAIN,
      NEXT_PUBLIC_EXPENSE_TRACKER_PROJECT_ID: process.env.NEXT_PUBLIC_EXPENSE_TRACKER_PROJECT_ID,
      NEXT_PUBLIC_EXPENSE_TRACKER_STORAGE_BUCKET: process.env.NEXT_PUBLIC_EXPENSE_TRACKER_STORAGE_BUCKET,
      NEXT_PUBLIC_EXPENSE_TRACKER_MESSAGING_SENDER_ID: process.env.NEXT_PUBLIC_EXPENSE_TRACKER_MESSAGING_SENDER_ID,
      NEXT_PUBLIC_EXPENSE_TRACKER_APP_ID: process.env.NEXT_PUBLIC_EXPENSE_TRACKER_APP_ID,
    },
  };
  
  export default nextConfig;
  